Absorb _ewtrc_derive_dirname into ewtrc; Streamline verbosity handling
Since we cannot source relative paths reliably, we have to resolve
EWT_HOME without relying on any other sources of code.

diff --git a/ewtrc b/ewtrc
--- a/ewtrc
+++ b/ewtrc
@@ -15,29 +15,37 @@
 #   before sourcing this script.)
 
 _ewtrc_cleanup() {
-  unset -v _verbose _all_safe var _on_home_or_user_lustre _on_user_lustre_only
-  unset -f derive_dirname set_research_programme
+  unset -v _ewtrc_verbose _all_safe var
+  unset -v _on_home_or_user_lustre _on_user_lustre_only
+  unset -f _ewtrc_derive_dirname set_research_programme
 }
 trap _ewtrc_cleanup RETURN
 
-[[ -v PBS_ENVIRONMENT || ! $- =~ "i" ]] && _verbose=0 || _verbose=1
+[[ -v PBS_ENVIRONMENT || ! $- =~ "i" ]] && _ewtrc_verbose=0 || _ewtrc_verbose=1
+export _ewtrc_verbose
 
 [[ ${BASH_SOURCE[0]} != "$0" ]] || {
-  ((_verbose)) && {
+  ((_ewtrc_verbose)) && {
     echo >&2 "ERROR: ${BASH_SOURCE[0]} (likely) not sourced, but executed."
   }
   exit 1
 }
 
+_ewtrc_derive_dirname() {
+  local full_path
+  full_path="$(realpath "$1" 2>/dev/null)" || {
+    ((_ewtrc_verbose)) && echo >&2 "ERROR: Unable to resolve realpath for $1."
+    return 3
+  }
+  echo "${full_path%/*}"
+}
+
 [[ -v EWT_HOME ]] || {
-  ((_verbose)) && {
-    echo -n "WARNING: EWT_HOME not set; attempting to derive as fallback..." >&2
+  ((_ewtrc_verbose)) && {
+    echo >&2 -n "WARNING: EWT_HOME not set; attempting to derive as fallback..."
   }
-  source src/derive_dirname.bash
-  EWT_HOME=$(derive_dirname -q "${BASH_SOURCE[0]}") || return 3
-  ((_verbose)) && {
-    echo "done."
-  }
+  EWT_HOME=$(_ewtrc_derive_dirname "${BASH_SOURCE[0]}") || return 3
+  ((_ewtrc_verbose)) && echo "done."
 }
 
 export USER_LUSTRE=/mnt/lustre/users/$USER
@@ -57,7 +65,7 @@ _on_user_lustre_only=(NXF_WORK NXF_SINGULARITY_CACHEDIR)
 _all_safe=1
 for var in "${_on_home_or_user_lustre[@]}"; do
   [[ ${!var} == $HOME/* || ${!var} == $USER_LUSTRE/* ]] || {
-    ((_verbose)) && {
+    ((_ewtrc_verbose)) && {
       echo >&2 "ERROR: $var must be on either $HOME or $USER_LUSTRE."
       echo >&2 "(Current target: ${!var} )"
     }
@@ -66,7 +74,7 @@ for var in "${_on_home_or_user_lustre[@]}"; do
 done
 for var in "${_on_user_lustre_only[@]}"; do
   [[ ${!var} == $USER_LUSTRE/* ]] || {
-    ((_verbose)) && {
+    ((_ewtrc_verbose)) && {
       echo >&2 "ERROR: $var must be on $USER_LUSTRE."
       echo >&2 "(Current target: ${!var} )"
     }
@@ -86,7 +94,7 @@ done
 # NOTE:   Users who belong to multiple groups must pass the desired
 #           RESEARCH_PROGRAMME string for a head job-style run via the -v option
 #           to qsub (or the corresponding #PBS line in the job script).
-source src/research_programme_handling.bash
+source "$EWT_HOME"/src/research_programme_handling.bash
 [[ -v RESEARCH_PROGRAMME ]] || set_research_programme -p -q >/dev/null 2>&1
 
 # FIXME:  This should not be set to false for interactive runs; i.e., when the
@@ -110,7 +118,7 @@ export NXF_DISABLE_CHECK_LATEST='true'
 # Run `less` with ANSI colors support (used in nextflow log files) by default.
 # alias less="less -R"
 
-source src/tless.bash
+source "$EWT_HOME"/src/tless.bash
 
 # Prevents $HOME from leaking into nextflow's singularity auto mounts via $PWD.
 alias cd="cd -P"
