Streamline handling for the EWT_HOME variable
While it's nice to subtly hint that it's better for the user to specify
EWT_HOME themselves, it also isn't the end of the world if they fall
back on the derivation logic we provide.

diff --git a/ewtrc b/ewtrc
--- a/ewtrc
+++ b/ewtrc
@@ -35,12 +35,9 @@ _ewtrc_derive_dirname() {
   echo "${full_path%/*}"
 }
 
-[[ -v EWT_HOME ]] || {
-  ((_ewtrc_verbose)) && {
-    echo >&2 -n "WARNING: EWT_HOME not set; attempting to derive as fallback..."
-  }
-  EWT_HOME=$(_ewtrc_derive_dirname "${BASH_SOURCE[0]}") || return 3
-  ((_ewtrc_verbose)) && echo "done."
+[[ -v EWT_HOME ]] || EWT_HOME=$(_ewtrc_derive_dirname "${BASH_SOURCE[0]}") || {
+  ((_ewtrc_verbose)) && echo >&2 "ERROR: Unable to resolve EWT_HOME."
+  return 3
 }
 
 export USER_LUSTRE=/mnt/lustre/users/$USER
